<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Lertaro.PluginSdk</AssemblyName>
    <RootNamespace>Lertaro.PluginSdk</RootNamespace>
    <Version>1.8.6</Version>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

</Project>
