<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Lertaro.Plugins.CoreExtensions</AssemblyName>
    <Version>1.5.4</Version>
      <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\PluginSdk\PluginSdk.csproj" Private="false" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Lertaro.Plugins.CoreExtensions.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Translations\**\*.json" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(TargetDir)$(TargetName).dll" DestinationFolder="..\..\App\bin\$(Configuration)\net10.0-windows\Plugins\" SkipUnchangedFiles="true" />
  </Target>
</Project>
